---
- include_vars: vars/brew.yml

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{var_items}}"